# Copyright 2023 Dimitri Koshkin. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-please-main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    # Map a step output to a job output
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3.7
        id: release-please
        with:
          release-type: go
          package-name: exec-assistant
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          changelog-notes-type: github

  release-tag:
    needs: release-please
    uses: ./.github/workflows/release-tag.yaml
    secrets: inherit
    if: ${{ needs.release-please.outputs.release_created }}
